settings:
  title: 'System Status'
  url: 'https://status.omerta.ai' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: omerta # unique identifier
    name: OMERTA
    description: 'Omerta' # default=empty
    url: 'https://api.omerta.ai/parse/health' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: api-qeventsdashboard-com # unique identifier
    name: QTI
    description: 'QTI API' # default=empty
    url: 'https://api.qeventsdashboard.com/parse/health' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: api-paysafecheckin-com # unique identifier
    name: PAYSAFE
    description: 'Paysafe API' # default=empty
    url: 'https://ps-api.eventcheckin.online/parse/health' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true